#!/usr/bin/env bash
# Build a fresh chunk graph from the current source tree.
#
# Output: .sisyphus/graphs/codebase.mmd (top-level packages) plus one
# .sisyphus/graphs/<package>.mmd per package (files within it). The
# graph is regenerated from scratch on each invocation — it is a
# function of the current commit, not state to preserve.
#
# Constraints:
#   - Production .go files only (no _test.go).
#   - Files over 400 LOC get a "⚠" marker so the readability heat map
#     can find them without re-scanning.
#   - .claude/ and worktree clutter is excluded; only the actual
#     source tree contributes nodes.

set -euo pipefail

repo_root="$(git rev-parse --show-toplevel)"
cd "$repo_root"

out_dir=".sisyphus/graphs"
mkdir -p "$out_dir"

# Discover packages. `go list ./...` is the right answer when go.mod is
# happy; fall back to a directory walk if not (no module loaded, etc).
if pkgs=$(go list ./... 2>/dev/null); then
  :
else
  pkgs=$(find . -name "*.go" -not -name "*_test.go" -not -path "./.claude/*" -not -path "./.git/*" -not -path "./eidos/*" \
    -exec dirname {} \; | sort -u | sed 's|^\./||')
fi

# Top-level graph: one node per package.
{
  echo "%% Auto-generated by .sisyphus/scripts/build_graph.sh — do not edit."
  echo "graph LR"
  while IFS= read -r pkg; do
    label="${pkg##*/}"
    # Trim repo prefix for readability.
    short_pkg="${pkg#github.com/jsevcu/dorian-mini}"
    short_pkg="${short_pkg#/}"
    [ -z "$short_pkg" ] && short_pkg="."
    safe_id=$(printf "%s" "$short_pkg" | tr './' '__')
    echo "  $safe_id[\"$label<br/><small>$short_pkg</small>\"]"
  done <<< "$pkgs"
} > "$out_dir/codebase.mmd"

# Per-package file graph.
while IFS= read -r pkg; do
  short_pkg="${pkg#github.com/jsevcu/dorian-mini}"
  short_pkg="${short_pkg#/}"
  [ -z "$short_pkg" ] && short_pkg="."
  pkg_dir="$repo_root/$short_pkg"
  [ -d "$pkg_dir" ] || continue
  safe_pkg=$(printf "%s" "$short_pkg" | tr './' '__')
  out_file="$out_dir/${safe_pkg}.mmd"
  {
    echo "%% Auto-generated by .sisyphus/scripts/build_graph.sh — do not edit."
    echo "%% Package: $short_pkg"
    echo "graph TD"
    for f in "$pkg_dir"/*.go; do
      [ -e "$f" ] || continue
      base="${f##*/}"
      case "$base" in *_test.go) continue ;; esac
      loc=$(wc -l < "$f")
      marker=""
      [ "$loc" -gt 400 ] && marker=" ⚠"
      safe_id=$(printf "%s" "$base" | tr '.' '_')
      echo "  $safe_id[\"$base<br/><small>$loc LOC$marker</small>\"]"
    done
  } > "$out_file"
done <<< "$pkgs"

# Heat map: every production file sorted by LOC descending. Files over
# the 400-line discipline ceiling stand out; the rest are noise the
# scoring scripts will refine into a real heat ranking.
{
  echo "%% Auto-generated by .sisyphus/scripts/build_graph.sh — do not edit."
  echo "%% File-size heat — sorted by LOC descending. ⚠ = > 400 LOC."
  echo "graph TD"
  find . -name "*.go" -not -name "*_test.go" -not -path "./.claude/*" \
    -not -path "./.git/*" -print0 |
    xargs -0 wc -l |
    grep -v ' total$' |
    sort -rn |
    head -40 |
    while read -r loc path; do
      base="${path##*/}"
      marker=""
      [ "$loc" -gt 400 ] && marker=" ⚠"
      safe_id=$(printf "%s" "${path#./}" | tr './-' '___')
      echo "  $safe_id[\"$base<br/><small>$loc LOC$marker</small>\"]"
    done
} > "$out_dir/heat.mmd"

echo "wrote: $out_dir/codebase.mmd"
echo "wrote: $out_dir/heat.mmd"
echo "per-package mmd files: $(ls "$out_dir"/*.mmd | grep -vE 'codebase|heat' | wc -l)"
