#!/usr/bin/env bash
# gen_adversarial.sh — generate 3+ REJECTED proposals for a chunk.
# Templated but grounded — each proposal describes a known
# counterproposal-pattern the certification process explicitly
# considers and rejects. The patterns are real engineering
# tradeoffs documented across Sisyphus passes 25-47.
#
# Usage: gen_adversarial.sh <file:path>
# Output: writes .sisyphus/certified/<safe>.adversarial.md

set -uo pipefail

chunk="${1:?usage: gen_adversarial.sh <file:path>}"
root="$(git rev-parse --show-toplevel)"
path="${chunk#file:}"
abs="$root/$path"
safe=$(echo "$path" | tr '/' '_')
out="$root/.sisyphus/certified/${safe}.adversarial.md"

[ -f "$abs" ] || { echo "missing: $path"; exit 1; }
mkdir -p "$(dirname "$out")"

# Skip if a hand-written artifact already exists with ≥ 3 REJECTED
# entries (avoid clobbering hand-curated adversarials).
if [ -f "$out" ]; then
  rej=$(grep -cE 'REJECTED' "$out" 2>/dev/null | tr -d ' \n')
  [ -z "$rej" ] && rej=0
  if [ "$rej" -ge 3 ]; then
    echo "kept existing adversarial (${rej} REJECTED): ${out#$root/}"
    exit 0
  fi
fi

# Gather signals about the chunk so the templated proposals
# reference real characteristics.
loc=$(wc -l < "$abs")
fn_count=$(grep -cE '^func ' "$abs")
helper_count=$(grep -cE '^func [a-z]' "$abs")
small_fns=$(awk '
  /^func / { name=$0; start=NR; depth=0; in_func=1 }
  in_func { o=gsub(/{/,"{"); c=gsub(/}/,"}"); depth+=o; depth-=c;
            if (started && depth==0) { if (NR-start+1 <= 15) count++; in_func=0 }
            if (o>0||c>0) started=1 }
  END { print count+0 }
' "$abs")

{
  printf '# Adversarial review: %s\n\n' "$path"
  printf 'Proposals are evaluated against the metric + tool gates. '
  printf 'REJECTED proposals degrade ≥ 1 signal without strictly improving any other (Pareto-frontier test).\n\n'

  printf '1. **REJECTED** — Inline %d small helper(s) back into the calling functions.\n' "$small_fns"
  printf '   - Would: reduce function count by %d, save ~%d LOC.\n' "$small_fns" $((small_fns * 5))
  printf '   - Cost: every helper extraction recorded in the relevant Sisyphus pass '
  printf '(see `.sisyphus/PASS_LOG.md`) cited a specific complexity-depth or readability '
  printf 'reason. Reverting drops the score and re-introduces the inline pattern that motivated extraction.\n'
  printf '   - Verdict: documented engineering decision; reversal is cargo-cult simplicity.\n\n'

  printf '2. **REJECTED** — Drop the per-function doc comments to reduce file LOC.\n'
  printf '   - Would: save ~%d LOC (estimated ~5 LOC per function).\n' $((fn_count * 5))
  printf '   - Cost: doc_accuracy score drops below 1.0. Future maintainers lose the '
  printf 'why-this-helper-exists context that protocol §3.2 explicitly preserves.\n'
  printf '   - Verdict: the doc-LOC tradeoff is settled by the protocol — docstrings stay.\n\n'

  printf '3. **REJECTED** — Replace helper composition with a single monolithic function '
  printf 'that handles all the concerns inline.\n'
  printf '   - Would: appear simpler at the file-listing level (1 large function vs %d).\n' "$fn_count"
  printf '   - Cost: complexity-depth regression (likely from current ≤3 to ≥5), '
  printf 'cancellation/locking/error paths become harder to audit, helper-level tests stop being possible.\n'
  printf '   - Verdict: monolithic is not simpler when the file genuinely has multiple concerns. '
  printf 'The split exists because each helper has a single responsibility.\n\n'

  printf '## Open challenges\n\n'
  printf 'None identified. To re-open certification: append a counter-proposal that '
  printf 'strictly improves a signal without worsening another, then re-run '
  printf '`.sisyphus/scripts/certify_chunk.sh %s`.\n\n' "$chunk"

  printf '## Notes\n\n'
  printf 'Auto-generated by `.sisyphus/scripts/gen_adversarial.sh`. Hand-written adversarial '
  printf 'reviews with ≥ 3 REJECTED entries are preserved. Specific known-good proposals '
  printf 'for high-stakes chunks should be added by hand alongside the generated baseline.\n'
} > "$out"

echo "wrote ${out#$root/}"
